server {
  listen 80;
  listen [::]:80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ =404;
  }

  location ~* \.(?:css|js|svg|png|jpg|jpeg|webp|woff2)$ {
    expires -1;
    add_header Cache-Control "no-cache";
    try_files $uri =404;
  }
}
